# Generated by Django 3.1.5 on 2024-10-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='King',
        ),
        migrations.RemoveField(
            model_name='user',
            name='thruth',
        ),
    ]
